/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SleeknoteUI;
import javax.swing.ImageIcon;
import java.awt.Image;
import SleeknoteUI.TelaVendas;
import javax.swing.JOptionPane;
import model.SessaoUsuario;
import model.Usuario;
import service.LogService;

/**
 *
 * @author vinic
 */
public class TelaPix extends javax.swing.JPanel {

    /**
     * Creates new form TelaPagamentoPix
     */
     LogService log = new LogService();
     
    public TelaPix(String total) {
        initComponents();

    lblValorPix.setText(total);

    ImageIcon icon = new ImageIcon(
        getClass().getResource("/frame.png")
    );

    Image img = icon.getImage().getScaledInstance(
            250,
            250,
            Image.SCALE_SMOOTH
    );

    lblQRCode.setIcon(new ImageIcon(img));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorPix = new javax.swing.JLabel();
        chavePix = new javax.swing.JLabel();
        lblQRCode = new javax.swing.JLabel();
        bntConfirmar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblValorPix.setText("R$");

        chavePix.setText("frutosgoias@pix.com");

        bntConfirmar.setBackground(new java.awt.Color(255, 153, 51));
        bntConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        bntConfirmar.setText("Confirmar");
        bntConfirmar.addActionListener(this::bntConfirmarActionPerformed);

        bntCancelar.setBackground(new java.awt.Color(255, 153, 51));
        bntCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(this::bntCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntCancelar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chavePix)
                        .addGap(127, 127, 127))))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lblValorPix)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorPix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQRCode, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chavePix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntConfirmar)
                    .addComponent(bntCancelar))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConfirmarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
                null,
                "Pagamento aprovado!"
        );
        
         log.registrar(SessaoUsuario.getUsuarioLogado().getNome(),"Vendeu um Produto" );
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    
    }//GEN-LAST:event_bntConfirmarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntConfirmar;
    private javax.swing.JLabel chavePix;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JLabel lblValorPix;
    // End of variables declaration//GEN-END:variables
}
