/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SleeknoteUI;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.SessaoUsuario;
import model.Usuario;
import repository.UsuarioRepository;
import service.LogService;

/**
 *
 * @author vinic
 */
public class TelaCadastroFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroFuncionarios
     */
    LogService log = new LogService();
    
    public TelaCadastroFuncionarios() {
        initComponents();
        carregarTabela();
        listarUsuario();
        
    }
     public void listarUsuario() {

        DefaultTableModel modelo = (DefaultTableModel) TabelaCadastroFuncionario.getModel();

        modelo.setRowCount(0);

        UsuarioRepository repository = new UsuarioRepository();

        for (Usuario u : repository.buscartodos()) {

            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getLogin(),
                u.getSenha(),
                u.getTipo()
            });

        }
    }
    public void carregarTabela() {
        
        DefaultTableModel modelo =
                (DefaultTableModel) TabelaCadastroFuncionario.getModel();

        modelo.setRowCount(0);

        UsuarioRepository repository =
                new UsuarioRepository();

        List<Usuario> lista = repository.buscartodos();

        for (Usuario u : lista) {

            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getLogin(),
                u.getSenha(),
                u.getTipo()
            });
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaCadastroFuncionariosDSK = new javax.swing.JDesktopPane();
        TxtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BntEditar = new javax.swing.JButton();
        BntCadastrar = new javax.swing.JButton();
        BntDeleta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaCadastroFuncionario = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        TxtSenha = new javax.swing.JTextField();
        TxtCargo = new javax.swing.JTextField();
        TxtId = new javax.swing.JTextField();
        TxtLogin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setForeground(new java.awt.Color(255, 204, 102));
        setIconifiable(true);
        setTitle("Tela Cadastro de Funcionarios");
        setToolTipText("3");
        setVisible(true);

        TelaCadastroFuncionariosDSK.setBackground(new java.awt.Color(255, 255, 204));

        TxtNome.addActionListener(this::TxtNomeActionPerformed);

        jLabel4.setText("Nome");

        jLabel5.setText("Senha");

        jLabel6.setText("Login");

        BntEditar.setBackground(new java.awt.Color(255, 153, 51));
        BntEditar.setForeground(new java.awt.Color(255, 255, 255));
        BntEditar.setText("Editar");
        BntEditar.addActionListener(this::BntEditarActionPerformed);

        BntCadastrar.setBackground(new java.awt.Color(255, 153, 51));
        BntCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BntCadastrar.setText("Cadastrar");
        BntCadastrar.addActionListener(this::BntCadastrarActionPerformed);

        BntDeleta.setBackground(new java.awt.Color(255, 51, 51));
        BntDeleta.setForeground(new java.awt.Color(255, 255, 255));
        BntDeleta.setText("Deletar");
        BntDeleta.addActionListener(this::BntDeletaActionPerformed);

        TabelaCadastroFuncionario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        TabelaCadastroFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Login", "Senha", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelaCadastroFuncionario.setShowGrid(false);
        TabelaCadastroFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCadastroFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaCadastroFuncionario);

        jLabel7.setText("Cargo");

        TxtSenha.addActionListener(this::TxtSenhaActionPerformed);

        TxtId.setEditable(false);
        TxtId.setEnabled(false);
        TxtId.addActionListener(this::TxtIdActionPerformed);

        TxtLogin.addActionListener(this::TxtLoginActionPerformed);

        jLabel8.setText("ID");

        TelaCadastroFuncionariosDSK.setLayer(TxtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(BntEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(BntCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(BntDeleta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(TxtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(TxtCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(TxtId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(TxtLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TelaCadastroFuncionariosDSK.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaCadastroFuncionariosDSKLayout = new javax.swing.GroupLayout(TelaCadastroFuncionariosDSK);
        TelaCadastroFuncionariosDSK.setLayout(TelaCadastroFuncionariosDSKLayout);
        TelaCadastroFuncionariosDSKLayout.setHorizontalGroup(
            TelaCadastroFuncionariosDSKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroFuncionariosDSKLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(TelaCadastroFuncionariosDSKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TelaCadastroFuncionariosDSKLayout.createSequentialGroup()
                        .addComponent(BntCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(BntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BntDeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaCadastroFuncionariosDSKLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel6)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(87, 87, 87))
                    .addGroup(TelaCadastroFuncionariosDSKLayout.createSequentialGroup()
                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
        TelaCadastroFuncionariosDSKLayout.setVerticalGroup(
            TelaCadastroFuncionariosDSKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroFuncionariosDSKLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(TelaCadastroFuncionariosDSKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaCadastroFuncionariosDSKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TelaCadastroFuncionariosDSKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntCadastrar)
                    .addComponent(BntEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BntDeleta))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(TelaCadastroFuncionariosDSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(TelaCadastroFuncionariosDSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("Tela de Cadastro de Funcionarios");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void BntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TabelaCadastroFuncionario.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione alguém na tabela para editar.");
            return;
        }

        try {
            model.Usuario func = new model.Usuario();
        
            // Seta o ID para que o 'atualizar' saiba qual registro alterar no banco
            int id = Integer.parseInt(TabelaCadastroFuncionario.getValueAt(linhaSelecionada, 0).toString());
            func.setId(id);
            func.setNome(TxtNome.getText());
            func.setLogin(TxtLogin.getText());
            func.setSenha(TxtSenha.getText());
            func.setTipo(TxtCargo.getText());

            repository.UsuarioRepository repo = new repository.UsuarioRepository();
            repo.atualizar(func);

            javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados!");
             log.registrar(SessaoUsuario.getUsuarioLogado().getNome(),"Editou um Funcionario" );
            listarUsuario();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
        }

    }//GEN-LAST:event_BntEditarActionPerformed

    private void BntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntCadastrarActionPerformed
        // TODO add your handling code here:
        // 1. Criar o objeto de modelo e preencher com os dados da tela
        model.Usuario novoUsuario = new model.Usuario();
        novoUsuario.setNome(TxtNome.getText());
        novoUsuario.setLogin(TxtLogin.getText());
        novoUsuario.setSenha(TxtSenha.getText());
        novoUsuario.setTipo(TxtCargo.getText()); // Assumindo que 'tipo' no seu modelo é o Cargo

        // 2. Chamar o repositório para salvar no banco
        repository.UsuarioRepository repo = new repository.UsuarioRepository();
    
        try {
            repo.salvar(novoUsuario); // Certifique-se de que o método no seu repo se chama 'cadastrar' ou 'salvar'
        
            // 3. Feedback para o usuário
            javax.swing.JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
            log.registrar(SessaoUsuario.getUsuarioLogado().getNome(),"Cadastrou um Funcionario" );
            // 4. Limpar os campos após o cadastro
            TxtNome.setText("");
            TxtId.setText("");
            TxtLogin.setText("");
            TxtSenha.setText("");
            TxtCargo.setText("");
            
            carregarTabela();
        
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage()); 
        }
        
        
    }//GEN-LAST:event_BntCadastrarActionPerformed

    private void BntDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntDeletaActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TabelaCadastroFuncionario.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um funcionário na tabela.");
            return;
        }

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir funcionário?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            try {
                
                int id = Integer.parseInt(TabelaCadastroFuncionario.getValueAt(linhaSelecionada, 0).toString());

                repository.UsuarioRepository repo = new repository.UsuarioRepository();
                model.Usuario usuarioParaRemover = repo.buscarPorId(id);

                if (usuarioParaRemover != null) {
                    repo.remover(usuarioParaRemover);
                    javax.swing.JOptionPane.showMessageDialog(this, "Funcionário removido com sucesso!");
                    log.registrar(SessaoUsuario.getUsuarioLogado().getNome(),"Removeu um Funcionario" );
                    carregarTabela(); 
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_BntDeletaActionPerformed

    private void TabelaCadastroFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCadastroFuncionarioMouseClicked
        // TODO add your handling code here:
        int linha = TabelaCadastroFuncionario.getSelectedRow();

    TxtId.setText(
        TabelaCadastroFuncionario.getValueAt(linha, 0).toString()
    );    
        
    TxtNome.setText(
        TabelaCadastroFuncionario.getValueAt(linha, 1).toString()
    );

    TxtLogin.setText(
        TabelaCadastroFuncionario.getValueAt(linha, 2).toString()
    );

    TxtSenha.setText(
        TabelaCadastroFuncionario.getValueAt(linha, 3).toString()
    );

    TxtCargo.setText(
        TabelaCadastroFuncionario.getValueAt(linha, 4).toString()
    );
       
    }//GEN-LAST:event_TabelaCadastroFuncionarioMouseClicked

    private void TxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSenhaActionPerformed

    private void TxtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginActionPerformed

    private void TxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntCadastrar;
    private javax.swing.JButton BntDeleta;
    private javax.swing.JButton BntEditar;
    private javax.swing.JTable TabelaCadastroFuncionario;
    private javax.swing.JDesktopPane TelaCadastroFuncionariosDSK;
    private javax.swing.JTextField TxtCargo;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtLogin;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtSenha;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
